[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/element/F7000000-0000-0000-0F08-000000000000/text
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC244910>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/element/F7000000-0000-0000-0F08-000000000000/text
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC245310>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/element/F7000000-0000-0000-0F08-000000000000/text
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC245A90>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC245D10>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC245F90>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC246490>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC246710>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC246990>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC246E90>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC247110>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC247390>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC244410>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC247890>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC247B10>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC34C050>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC34C2D0>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000274BC34C550>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session/d428a14e9576b3a20b6dafa3f3be1940e5a396d6