{"name": "test_valid_login", "status": "skipped", "statusDetails": {"message": "Skipped: Unexpected error while creating driver: WebDriver.__init__() got an unexpected keyword argument 'desired_capabilities'\n\nTraceback (most recent call last):\n  File \"C:\\assignment\\mobile_ios\\conftest.py\", line 61, in driver\n    driver = webdriver.Remote(command_executor=hub, desired_capabilities=caps)\nTypeError: WebDriver.__init__() got an unexpected keyword argument 'desired_capabilities'", "trace": "('C:\\\\assignment\\\\mobile_ios\\\\tests\\\\test_login.py', 12, 'Skipped: Unexpected error while creating driver: WebDriver.__init__() got an unexpected keyword argument \\'desired_capabilities\\'\\n\\nTraceback (most recent call last):\\n  File \"C:\\\\assignment\\\\mobile_ios\\\\conftest.py\", line 61, in driver\\n    driver = webdriver.Remote(command_executor=hub, desired_capabilities=caps)\\nTypeError: WebDriver.__init__() got an unexpected keyword argument \\'desired_capabilities\\'')"}, "description": "User can log in with valid credentials.", "start": 1758002227299, "stop": 1758002227299, "uuid": "4f61e263-49b7-4741-8205-ed15a74ef776", "historyId": "27b150db6705ef6511c7ecb21ff68d02", "testCaseId": "ab68c09e23714aa68c720c2ca07c0ecf", "fullName": "tests.test_login#test_valid_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "5140-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}