[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002943E017620>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002943E08CE10>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002943E08D310>: Failed to resolve 'hub-cloud.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session